### ISSUE TITLE
Is it possible to render Symfony forms?

### ISSUE THREAD

**Issue by harunyasar** [thephpleague/plates#100]
I want to use Symfony form component outside of Symfony framework. Is it possible to use Symfony forms in Plates with full functionality?

**Comment by ricardofiorani** [comment]
Symfony Form component is independent of a Template Engine (it can runs on pure PHP), so I think there will be no trouble to use it with Plates. All you gotta do is to tell to your controller to render using plates sending your Symfony Form data to your view, in there it's just like the usual.
In [this](http://symfony.com/doc/current/cookbook/form/form_customization.html) page you can see both twig and pure php examples.

**Comment by harunyasar** [comment]
Thanks for your information.
