### ISSUE TITLE
Install without Composer?

### ISSUE THREAD

**Issue by robinson-risquez** [thephpleague/plates#101]
Hi, I'm new to Plates and wish there was a method "offline" to install Plates, because I do not like to depend on Composer to install it. Is there any way to install without composer? Thanks.

**Comment by rogerroelofs** [comment]
Composer has worked well for us.  But you can just download the repo if you prefer.  Just go the main repo page and 'Download ZIP'

**Comment by reinink** [comment]
Yep, as @rogerroelofs mentioned, you can just download the package as a zip file. More instructions found here: http://platesphp.com/installation/#downloading-zip-file

I would highly recommend that you do use Composer. It's really the future of PHP, and makes managing dependencies a LOT easier.

Good luck!
