### ISSUE TITLE
Escape helper works only with UTF8

### ISSUE THREAD

**Issue by userlond** [thephpleague/plates#106]
https://github.com/thephpleague/plates/blob/master/src/Template/Template.php#L268

Current implementation of escape filter works only with UTF8-encoded data. Suggest the way to configure default encoding and use it inside such helpers.

**Comment by reinink** [comment]
I think it would be good to add a new configuration option for this:

```php
// Create new Plates engine
$templates = new League\Plates\Engine('/path/to/templates');

// Set charset
$templates->setCharset('ISO-8859-1');
```

We'd still use `UTF-8` as the default.

**Comment by ragboyjr** [comment]
Closing in favor of #171
