### ISSUE TITLE
Twig-like "blocks" using output buffering

### ISSUE THREAD

**Issue by jurchiks** [thephpleague/plates#107]
It is possible to use output buffering to create Twig-like block functionality.
I've created an example Gist here: https://gist.github.com/jurchiks/f98da6959ba726a782ce
It works perfectly as expected (you need PHP 7 though, because I used `string` type hints).

It would be great if something like this was included in Plates.

**Comment by jurchiks** [comment]
Whoops, looks like you already have this, but it's called "sections" and not "blocks"...

**Comment by reinink** [comment]
Yepper! [Sections](http://platesphp.com/templates/sections/) and [inheritance](http://platesphp.com/templates/inheritance/) are modelled after Twig's block functionality. :+1:
