### ISSUE TITLE
Automatic escaping

### ISSUE THREAD

**Issue by inxilpro** [thephpleague/plates#109]
The [plates website states](http://platesphp.com/templates/escaping/):

> Probably the biggest drawbacks to native PHP templates is the inability to auto-escape variables properly.

It seems to me that this would be quite easy to implement. Something like:

```php
public function data(array $data)
{
	$this->raw = array_merge($this->raw, $data);

	array_walk_recursive($data, function(&$item, $key) {
		if (is_string($item)) {
			$item = $this->escape($item);
		}
	});
	$this->data = array_merge($this->data, $data);
}

public function unescaped($key)
{
	return $this->raw[$key];
}
```

Then, if you wanted the escaped version, you just use it, and call `unescaped` if you need the raw version:

```php
Hello <?=$name?>!
<?=$this->unescaped('html_code')?>
```

It would also be quite easy to make this opt-in—just check for a boolean flag in `data()` and `unescaped()`, skip the new code in the former, and return from `$this->data` instead of `$this->raw` in the latter.

**Comment by inxilpro** [comment]
Actually, never mind :)  If you're dealing with objects, this would fail.

**Comment by reinink** [comment]
Yeah, I've tried to solve the automatic escaping thing in the past, but have come to the conclusion it cannot be done properly without a compilation step. If you want to read through all the (boring) findings, see:

https://github.com/thephpleague/plates/issues/21
https://github.com/thephpleague/plates/issues/24
https://github.com/thephpleague/plates/issues/23
