### ISSUE TITLE
Website docs

### ISSUE THREAD

**Issue by CoolGoose** [thephpleague/plates#112]
Hello there, my google fu seems to be broken, where can I submit a pull request for updating the website (the changelog on the site is only at 3.1.0 for eg).

**Comment by baileylo** [comment]
https://github.com/thephpleague/plates/tree/gh-pages

**Comment by baileylo** [comment]
https://github.com/thephpleague/plates/tree/gh-pages

**Comment by CoolGoose** [comment]
Thanks :+1:
