### ISSUE TITLE
Problem with nested section()

### ISSUE THREAD

**Issue by jkhaled** [thephpleague/plates#113]
I have three nested templates
layout > home > list  (list included inside home wich is also included in layout)
with 

``` php
echo $this->section('javascript') 
```

in layout and  in both home and list have

``` php
 $this->start('javascript'); 
```

the problem that when rendering template it displays the **javascript** section of _'list'_ template otherwise concatenate  the two

**Comment by ragboyjr** [comment]
@jkhaled are you still having issues with this?

**Comment by reinink** [comment]
@jkhaled I'm going to close this for now, but if you still need help please feel free to update this issue!
