### ISSUE TITLE
Update docs - PHP short tags

### ISSUE THREAD

**Issue by paulera** [thephpleague/plates#115]
Documentation needs to be updated since short tags `<?= ... ?>` are no longer available in PHP 7.0 : http://php.net/manual/en/language.basic-syntax.phptags.php

**Comment by rogerroelofs** [comment]
Actually the docs don't say that.  Only <%, %>, <%=, and the script tag
<script language="php"> are removed.

On Thu, Mar 31, 2016 at 10:32 AM, Paulo Amaral <notifications@github.com>
wrote:

> Documentation needs to be updated since short tags <?= ... ?> are no
> longer available in PHP 7.0 :
> http://php.net/manual/en/language.basic-syntax.phptags.php
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/thephpleague/plates/issues/115>
>



-- 
Roger

Roger Roelofs
Know what you value.

**Comment by reinink** [comment]
Yeah, sort *echo* tags are always available:

> The tag <?= is always available regardless of the short_open_tag ini setting.

Short short *open* tags are the other hand are discouraged.

**Comment by paulera** [comment]
True, sorry for the misunderstood! Phew!
