### ISSUE TITLE
Blank (broke) page when data passed to template is "too big"

### ISSUE THREAD

**Issue by bastienff** [thephpleague/plates#119]
Hello, i am triying to pass a "big" array to the template (like 200 records) but it break all the system, show nothing, only a white screen, not even an error.

If i limit the select query, it start working again (limiting the query to 6 or 10 records, depending the length of the data array).

**Comment by rogerroelofs** [comment]
I'm betting you will find an out of memory error in the php error log.  This is a php issue, not a plates issue per se.  There are multiple ways around this but we would need to see your code to offer any coherent suggestions.

**Comment by bastienff** [comment]
I found the problem, i was using ob_start(); ob_end_flush(); because i am getting this error:

```
Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to emit response; headers already sent' in F:\xampp\htdocs\sistema\vendor\zendframework\zend-diactoros\src\Response\SapiEmitter.php on line 31
#0: Zend\Diactoros\Response\SapiEmitter:emit F:\xampp\htdocs\sistema\index.php:51
```

At the end nothing to do with plates. Thanks for the help.
