### ISSUE TITLE
Referencing foreach elements

### ISSUE THREAD

**Issue by joakinen** [thephpleague/plates#120]
Trying to use the syntax example in http://platesphp.com/templates/syntax/ I found what seems a mistake in the way the elements in the array are referenced.

This is the code from the example:

> ```
> <?php foreach($friends as $friend): ?>
>     <li>
>         <a href="/profile/<?=$this->e($friend->id)?>">
>             <?=$this->e($friend->name)?>
>         </a>
>     </li>
> <?php endforeach ?>
> ```

For showing the "id" or "name" element inside foreach loop I had to use this notation

> <?=$friend['name'] ?>
> 
> <?=$friend['id'] ?>

instead of 

> <?=$this->e($friend->name)?>

as this notation doesn't show anything at all.

Am I missing something?

**Comment by baileylo** [comment]
This depends on each individual setup. If your `$friends` variable is an array of arrays or an array of objects:

```
$friend_1 = ['id' => 5, 'name' => 'John Jacob'];
$friend_2 = ['id' => 9, 'name' => 'Jingleheimer Schmidt']

$template = $templates->make('friends', [$friend_1, $friend_2]);
```
In the above case the `$friend` variable will be an array and should be accessed using `$friend['id']`.

```
class Friend {
    public $id, $name;
    public function __construct($id, $name)
    {
        $this->id = $id;
        $this->name = $name;
    }
}

$friend_1 = new Friend(5, 'John Jacob');
$friend_2 = new Friend(9, 'Jingleheimer Schmidt');

$template = $templates->make('friends', [$friend_1, $friend_2]);
```

In the above case the `$friend` variable will be a `Friend` object and should be accessed using `$friend->id`.

**Comment by joakinen** [comment]
Thank you for clarifying that difference!

**Comment by ragboyjr** [comment]
@joakinen can we close this?
