### ISSUE TITLE
Escape multiple variables by reference

### ISSUE THREAD

**Issue by cdCorey** [thephpleague/plates#121]
I understand that auto-escaping isn't feasible, but I believe we could still improve things in this area by simply offering a method to mass-escape multiple variables at once. For example, we could then have this at the top of a template:

```
$this->escapeMultiple($foo, $bar, $baz);
```

And that would allow the actual template code to be much cleaner:

```
<h1><?=$foo?></h1>
<div><?=$bar?></div>
<div><?=$baz?></div>
```

This way the template author still has to think about escaping, but they only have to do it once at the top. If they've escaped some variables and not others, this is nicely self-documenting, as they can glance back up to the top if they need to check whether a particular variable has been escaped already. It's not quite as slick as full-blown auto-escaping, but this feels like it would be a middle ground that's better than the current requirement of manually escaping every single time, without running into the problems associated with auto-escaping.

I tried to write an extension to add this (which was going to support both strings and arrays of strings), but discovered it seems to be impossible to add as an extension given the current architecture, because template functions cannot receive data by reference.

Any chance of this being added as an official feature? If not, any chance of making it possible for template functions to get data by reference, so I can at least finish my extension?

**Comment by reinink** [comment]
Hey @cdCorey, I'm thinking on this one, and will get back to you! 👍

**Comment by cdCorey** [comment]
Thanks for replying. I'm using a [non-extension version of this](https://gist.github.com/cdCorey/d14ad407fa72b3781173888a941abf56) in a couple templates right now, and it seems to work well for its intended purpose of escaping string variables and arrays filled with strings. It would definitely be more convenient to use as an extension, though.

A slightly more in-depth approach to this – and maybe this is adding more weight than desired, I'll let you be the judge of that – would be to offer the option of registering a template's variables at the top. That would, again, be self-documenting as to what can be expected in the template, but the main uses that spring to mind for me would be to allow variables to be flagged for auto-escaping, or flagged as required (in which case a template might throw an error if the variable is missing). This would also be a good place to set defaults for optional variables.

Right now, I find myself writing code to do a lot of that at the top of each template, and that works fine. But maybe there would be benefit to adding a more structured way of handling that (if nothing else, it would encourage template authors to stick that stuff at the top, which I at least feel is a better place for it than mixed into the template).

**Comment by ragboyjr** [comment]
@cdCorey, You could also just escape a set of variables before you render the data.

```php
<?php

$engine->render('template', escapeData([
  'field' => '<html>a</html>'
]));
```

`escapeData` is a made up function, but i'm sure you can find a package or create it yourself.

Would something like that not work?

**Comment by reinink** [comment]
In general this type of function scares me a little since the escaping doesn't happen at the exact point of output. I think this could lead to security issues. For example, maybe you add some extra output down the road, but you forget to the update the `escapeMultiple()` call earlier.

I would go with @ragboyjr's suggestion and create a helper function for this. I would have thought this would be possible as an extension as well, since all extensions have access to the current template via the public $template property. Using that you could modify (escape) the data of that template, and save it back to the template itself.

Not tested at all, but it would look something like this:

```php
class EscapeMultiple implements ExtensionInterface
{
    public $template;

    public function register(Engine $engine)
    {
        $engine->registerFunction('escapeMultiple', array($this, 'escapeMultiple'));
    }

    public function escapeMultiple(...$vars)
    {
        // escape the vars

        $this->template->data($vars);
    }
}
```

**Comment by cdCorey** [comment]
@reinink, I have to admit I'm a bit frustrated by the contradiction in your latest response. It's fine that you disagree with my suggestion, but if that's because you think moving escaping away from output is a bad idea, how can you then turn around and say moving it _even further_ away from output is a good idea?

While I appreciate @ragboyjr's suggestion, I do think it's off the mark. Not only does escaping when the template is called further separate escaping from output, but it requires repetition of escape code every time the template is used, and breaks separation of concerns because now every piece of code that calls the template also has to know precisely how the template is going to use its input—and as a result, any change to how the template uses its input has the potential to break and require updates to every single piece of code that calls the template. Even in a hypothetical best case scenario where the template's internal logic never changes, requiring every developer to know and remember exactly which variables to escape every single time they call every single template seems far more prone to cause security issues due to human error. It's just not a good solution.

I agree with the current approach to escaping insofar as that I absolutely think it belongs in the template. This keeps things DRY, maintains single responsibility, keeps escaping packaged with output, etc. 

Anyway, a custom extension is a perfectly acceptable solution. My only real issue was that, as far as I could tell at the time, it didn't seem to be possible to get this working as an extension. However, I may not have been aware there was a template->data() function to let me overwrite the existing template variables. If that's the correct way to do it, that should solve my issue. I'll give it another shot when I get a chance, and if I get an extension to do this working I'll link it here for anyone else who wants it. Thank you for the assistance.

**Comment by reinink** [comment]
First off, sorry you're frustrated. That was certainly not my intention. We're doing our best.

My point isn't _where_ the escaping logic is kept, it's about where it's called. Sorry if I didn't make that clearer. I think that if you're using native PHP templates you should be doing the escaping at the exact point of output, and really to every single variable that you output regardless of whether it's considered "safe" or not.

I've spent more hours than I'd like to admit trying to improve escaping in Plates, and this is where I've landed. There are limits on what can be done with native PHP when it comes to escaping. This is actually a big reason why I recommend developers use a library that supports automatic escaping, such as Twig or Blade. (I understand that might seem odd coming from the developer of a native PHP templating library.)

Creating an extension to do this should be pretty straight forward. Let us know if you run into any issues with that!

**Comment by cdCorey** [comment]
@reinink, it was just a bit confusing that you expressed support for @ragboyjr's suggestion when that directly contradicted the reason you said you disagreed with my suggestion. Your response doesn't really address that, but it does reiterate the same position you've expressed consistently everywhere else, so I have to assume there was just some kind of miscommunication. Happens all the time on the Internet, so no worries.

I'm not sure how escaping "every single variable that you output regardless of whether it's considered 'safe' or not" would work, though. I often need to pass HTML content to templates. That can't be escaped without breaking the markup, or am I missing something?

**Comment by reinink** [comment]
> I often need to pass HTML content to templates. That can't be escaped without breaking the markup, or am I missing something?

Correct, you wouldn't escape those. I mean all variables, except those that must be outputted raw.

**Comment by cdCorey** [comment]
@reinink, the call to `$this->template->data($vars)` doesn't appear to be working. I can echo properly escaped `$vars` within my extension right up to the line where I push it to the template, so I know the rest is working, but when I output the variables in an actual template, they're not coming out escaped. I looked at the code for `data()` and it certainly looks like what you suggested _should_ work, though. Pretty weird. Any thoughts you'd be willing to share?

`class EscapeMultiple implements ExtensionInterface {
	
	public $template;
	
	public function register(Engine $engine) {
		$engine->registerFunction('escapeMultiple', [$this, 'escape_multiple']);
	}
	
	/**
	 * Escapes multiple string variables or arrays of strings by reference.
	 * 
	 * This is the public API call. It tests provided data, and if any non-string data 
	 * is received, throws an exception without making changes. If all data passes, it 
	 * loops through all strings and replaces them with escaped strings.
	 *
	 * @param    string|string[] $vars... Any number of string variables or arrays of strings to be escaped.
	 * @return   void
	 */
	public function escape_multiple(...$vars) {
		if ( !$this->are_all_strings($vars) ) {
			throw new Exception('escape_multiple() received inescapable data!');
		}

echo 'UNESCAPED: ';
print_r($vars);
		$vars = $this->escape_confirmed_strings($vars);
echo 'AFTER ESCAPING: ';
print_r($vars);
		$this->template->data($vars);
	} // escape_multiple()

	/**
	 * Escapes pre-tested array of strings and/or arrays of strings by reference.
	 *
	 * @param    string[] $vars Array of strings and/or arrays of strings to be escaped.
	 * @return   void
	 */
	private function escape_confirmed_strings($vars) {
		foreach ($vars as &$v) {
			if ( is_array($v) ) {
				// Escape each array element
				$v = $this->escape_confirmed_strings($v);
			} else {
				$v = $this->escape_confirmed_string($v);
			}
		} // foreach
		
		return $vars;
	} // escape_confirmed_strings()
	
	/**
	 * Escapes one pre-tested string variable by reference.
	 *
	 * @param    string $var One string variable to be escaped.
	 * @return   void
	 */
	private function escape_confirmed_string($var) {
		$var = $this->template->escape($var);
		echo "ESCAPE: $var\n\n";
		return $var;
	} // escape_confirmed_string()

	/**
	 * Confirms all non-empty values in array are either strings or arrays of strings.
	 * 
	 * If ANY non-string/non-string-array value is found, test immediately fails.
	 *
	 * @param    string $var A variable to test.
	 * @return   bool Indicates whether all values are strings.
	 */
	public function are_all_strings(array $vars) {
		foreach ($vars as $v) {
			if ( !empty($v) ) {
				if ( is_array($v) ) {
					// Check each array element
					$valid = $this->are_all_strings($v);
					
					if (!$valid) return false;
				}
				elseif ( !is_string($v) ) {
					return false;
				}
			} // if !empty
		} // foreach

		// If we got here, everything passed!
		return true;
	} // are_all_strings()
	
} // class
`

**Comment by ragboyjr** [comment]
@cdCorey it looks like you are calling `data()` wrong. `data` expects an associative array of `varname => value`. You are passing in an array of values, not an associative array of names to values. So those values will NOT be escaped. ALSO, i'm not sure that calling data will also extract the variables properly.

`$template->data(['container_classes' => $container_classes])`.

You'd have to accept them by reference because you're just escaping new values, but not actually escaping the variables inside of the template.

Right now, you are accepting copies of the values you provided.

And i'm not even sure you could properly capture variables by reference

**Comment by ragboyjr** [comment]
This is different than your current approach, but maybe you could try injecting a function into the data like so.

```
<?php

$template->data(['e' => function($v) use ($template) {
  return $template->escape($v);
});
```

Then in your template, you can simply escape via `<?=$e($var)?>`

This is a departure from what your are trying to do, but it could definitely be implemented and might be just enough for what you need.

**Comment by cdCorey** [comment]
@ragboyjr, if you look at the title of this issue, you'll note my request in the first place was to make it possible to pass the template variables to an extension by reference, because that seems to be impossible with the current architecture. I only tried the `data()` function at the recommendation of @reinink, but it appears his suggested code won't work because the template's data array is extracted before the extension can be called. Bottom line, making changes to the template's variables from within an extension is simply not supported by Plates's current architecture.

Since my original request has already been rejected and closed, it doesn't look like that limitation is going to change, so I'll just have to keep using an external function to do this. I think it would be cleaner as a Plates extension, but c'est la vie. Thanks to both of you for taking the time to offer some suggestions.

**Comment by ragboyjr** [comment]
@cdCorey, another thought...

You could also just create your own function to escape multiple and inject into your templates..... It doesn't need to be apart of the plates template class. 

```php
<?php

$escapeMulti = function(&...$vars) {
     foreach ($vars as &$var) { 
        $var = htmlentities($var);
    }
};
$engine->addData(['escapeMulti' => $escapeMulti]);
```

In the template

```php
<?php $escapeMulti($var1, $var2) ?>
```
