### ISSUE TITLE
Documentation on Getting Started with Plates

### ISSUE THREAD

**Issue by teamcoltra** [thephpleague/plates#128]
I finally figured it out, more or less... but it would be nice to have a demo site or boilerplate to really get a feel for plates. The controller in the getting started guide doesn't actually explain what everything is doing.

I get 

`echo $templates->render('profile', ['name' => 'Jonathan']);`

renders the template /path/to/templates/profile.php

and that template calls on /path/to/templates/template.php to generate the overall structure... 

but I don't know, doing anything past that seems confusing. To be fair I don't work with objects very frequently or any of this stuff, so this is on me, but at least for me seeing code in action makes it much easier to learn it. I know you should be spending your time actually making the code better (or working on other projects) than to spend your time with extra documentation that only people like me need... but seeing some basic project code with the tools from the engine actually working and how it all works together would be useful.

**Comment by ragboyjr** [comment]
@teamcoltra 

> The controller in the getting started guide doesn't actually explain what everything is doing.

Their is more extensive documentation on the specific aspects to Plates in the documentation. What aspect of the engine or template system is left out?

**Comment by teamcoltra** [comment]
I don't know reading through it now it all makes sense and is coming together but it seems like when I actually start using it I keep running into trouble. I will go back to writing and if something comes up I will re-open the request :)

**Comment by ragboyjr** [comment]
np man, Thanks

**Comment by teamcoltra** [comment]
Okay so here is just a quick example I ran into - not the end of the world, but on http://platesphp.com/templates/layouts/

Where does the $article object come from? It's used but never described (as far as I can tell). Is this just a case of someone passing an object instead of using an array?

**Comment by ragboyjr** [comment]
No - Check Here - http://platesphp.com/templates/data/

It would have been from someone rendering with an author object like so:

```$engine->render('path', ['article' => $article]);```
