### ISSUE TITLE
I need help creating a section

### ISSUE THREAD

**Issue by mateoagudelo** [thephpleague/plates#129]
I have this: 

index.php:
`<?php
require 'vendor/autoload.php';
$plantillas = new League\Plates\Engine('views');
$plantillas->addFolder('public', 'views/public');
echo $plantillas->render('public::header');
echo $plantillas->section('contenido');
?>`

views/public/header.php:
`<!DOCTYPE html>
<html>
<head>
<title>Hola esta es la plantilla</title>
</head>
<body>

</body>
</html>

<p>Hola<p>
<?php $this->start('contenido'); ?>
<p>Welcome!</p>
<?php $this->stop(); ?>`

I get the following error:
Fatal error: Uncaught Error: Call to undefined method League\Plates\Engine::section() in C:\xampp\htdocs\plate\index.php:6 Stack trace: #0 {main} thrown in C:\xampp\htdocs\plate\index.php on line 6

Please help!

**Comment by ragboyjr** [comment]
@mateoagudelo are you still having issues with this?

**Comment by reinink** [comment]
Closing this for now. If you still need help @mateoagudelo, please feel free to continue the discussion here.
