### ISSUE TITLE
Confusing example on Syntax page on the website

### ISSUE THREAD

**Issue by zzzanderw** [thephpleague/plates#144]
On the [Syntax](http://platesphp.com/templates/syntax/) page for Plates, there is an example:
```
<?php $this->layout('template', ['title' => 'User Profile']) ?>

<h1>Welcome!</h1>
<p>Hello <?=$this->e($name)?></p>

<h2>Friends</h2>
<ul>
    <?php foreach($friends as $friend): ?>
        <li>
            <a href="/profile/<?=$this->e($friend->id)?>">
                <?=$this->e($friend->name)?>
            </a>
        </li>
    <?php endforeach ?>
</ul>

<?php if ($invitations): ?>
    <h2>Invitations</h2>
    <p>You have some friend invites!</p>
<?php endif ?>
```
The line with `<?php foreach($friends as $friend): ?>` is puzzling to me. Does this mean that I can define an array `$friends` in the file that initializes the engine and renders the template? I tried to do that, but it didn't work. I am puzzled because `$friends` isn't being referenced using `$this->e($friends)` like it would be normally.

Any light somebody could shed on this would much appreciated. I am currently trying to figure out how to pass arrays into a Plates template.

**Comment by rogerroelofs** [comment]
As long as $friends is passed in the data array in the code that renders the template it should work fine.  The point of the page is to describe stylistic best practice for template code and so doesn't include the code that would be used to render the template.

**Comment by reinink** [comment]
Yes, as @rogerroelofs noted, the assumption here is that you have passed friends to your template from your controller, or elsewhere. This isn't a complete example, but rather an example of what the  syntax can/should look like.

**Comment by zzzanderw** [comment]
Ok, thank you. I thought you always had to use `$this->e($friends)` to access data. Glad to see I am not forced to escape everything :).

**Comment by reinink** [comment]
Oh, right, sorry, I missed that part. You only need to escape when outputting variables. In that situation you are looping (using foreach), which doesn't output anything, so you don't need to escape there.
