### ISSUE TITLE
Extensions as widget

### ISSUE THREAD

**Issue by kamov** [thephpleague/plates#146]
I would like to know if extension can be used as sort of widget?
I mean to display complex data like a menu which is build dynamically from database?
If extension contain database query, this is executed only when is called within template right?
Thanks

**Comment by ragboyjr** [comment]
@kamov this is possible, since the function would only be invoked once you call it from template.

I'd recommend using a service to actually do your database call or rendering, and then register the extension with that service injected into the constructor of the extension.

**Comment by ragboyjr** [comment]
Closing since this has been answered.
