### ISSUE TITLE
How to load library files from assets and bower_components folder?

### ISSUE THREAD

**Issue by MisterGeorge** [thephpleague/plates#148]
What would be the '/ path / to / bower_components /' to use libraries and load the project's own styles, within Base_Controller charge: $ this-> templates-> loadExtension (new League \ Plates \ Extension \ Asset (getcwd . '/ Assets /', true)); But they do not load the files or simply tell me that they are not found on that path.

**Comment by ragboyjr** [comment]
@MisterGeorge are you still struggling with this? Your issue description isn't entirely descriptive, but I think I think you are just using the wrong path to the public assets folder.
