### ISSUE TITLE
asset extension path issue

### ISSUE THREAD

**Issue by fatcat386** [thephpleague/plates#149]
Hello!
There is issue in asset extension. This part of code:

```
        if ($pathInfo['dirname'] === '.') {
            $directory = '';
        } elseif ($pathInfo['dirname'] === '/') {
            $directory = '/';
        } else {
            $directory = $pathInfo['dirname'] . '/';
        }
```

should be written as:

```
        if ($pathInfo['dirname'] === '.') {
            $directory = '';
        } elseif ($pathInfo['dirname'] === '/' || $pathInfo['dirname'] === '\\') { // HERE !!!
            $directory = '/';
        } else {
            $directory = $pathInfo['dirname'] . '/';
        }
```

otherwise it is not work on Windows in some cases.

For example, this not work without improvement:
`<link rel="shortcut icon" type="image/x-icon" href="<?=$this->asset('/favicon.ico')?>">`
But this works:
`<link rel="stylesheet" type="text/css" href="<?=$this->asset('/css/style.css')?>">`

Thank you!

**Comment by mitry** [comment]
Maybe something like:
```
} elseif ($pathInfo['dirname'] === DIRECTORY_SEPARATOR ) {
            $directory = DIRECTORY_SEPARATOR;
} else {
            $directory = $pathInfo['dirname'] . DIRECTORY_SEPARATOR;
}
```

**Comment by fatcat386** [comment]
Just tested your code. Yes you right. My testing shows that $pathInfo['dirname'] returns OS dependent slash for such "/cases" (root resource) and not touches them in other cases.

But I not like OS dependent separators in output as I always supply forward slashed urls.

So maybe:

```
} elseif ($pathInfo['dirname'] === DIRECTORY_SEPARATOR ) {
    $directory = '/';
} else {
    $directory = $pathInfo['dirname'] . '/';
}
```

Or we can replace backslashes in $pathInfo['dirname'] with forward slashes. Anyway whole function expects forward slashed input. See ltrim on beginning.

**Comment by ragboyjr** [comment]
@fatcat386 this looks great, do you want to submit an MR?
