### ISSUE TITLE
Setting sections programmatically

### ISSUE THREAD

**Issue by guilhermeaiolfi** [thephpleague/plates#150]
Hi,

I'm trying to use Plates a little bit different. I want to replicate what Agavi Framework does. The only missing feature is a way to set sections programmatically as:

```php
$template->setSection('section_name', $section_content);
```

That way I could produce the section content elsewhere and consume them inside the template when rendering. Am I missing something or it ins't possible currently? Would you be interested in a pull request adding that feature?

**Comment by ragboyjr** [comment]
Can't you just do:

```
$template->start();
echo $section_content;
$template->stop();
```

**Comment by guilhermeaiolfi** [comment]
Oh, sorry. Worked perfectly. I should have though about it.  Thanks.

**Comment by ragboyjr** [comment]
NP man. have a good one.
