### ISSUE TITLE
Conflict with $this->session->userdata() codeigniter - plates

### ISSUE THREAD

**Issue by adolfoamaris** [thephpleague/plates#158]
Hello, I implemented plates in codeigniter 3 and I have a conflict when trying to 
`echo $ this-> session-> userdata ("username");`      with the following message:

How could I solve it?

<h4>A PHP Error was encountered</h4>

<p>Severity: Notice</p>
<p>Message:  Undefined property: League\Plates\Template\Template::$session</p>
<p>Filename: views/main.php</p>
<p>Line Number: 202</p>

Thank you

**Comment by ragboyjr** [comment]
`$this` is a reference to the Plates Template i believe, and not the CI super global. you'll need to do something like `get_instance()->session` or pass in the CI object as a global to the Plates Engine.

**Comment by physcocode** [comment]
CI_Controller is the superglobal used in CI to get instances if session etc. In extension to @ragboyjr's answer

**Comment by ragboyjr** [comment]
@adolfoamaris can we close this?
