### ISSUE TITLE
Minimum PHP Requirements

### ISSUE THREAD

**Issue by ragboyjr** [thephpleague/plates#160]
We need to consider about moving up the minimum php requirements to maybe 5.5 or 5.6+. Travis builds are currently failing for 5.3, so we should at least get rid of that.

**Comment by funivan** [comment]
Maybe 7.0 ?

**Comment by rogerroelofs** [comment]
I think 5.6 is still used in enough places that it should be supported.

**Comment by ragboyjr** [comment]
Not sure how recent this is, but 5.5 represents 10% of the users and 5.6 being 30%. So, going to 7.0 could alienate a lot of users, and i get the feeling that we have a lot of consumers with older than normal php versions with this repo. I've seen several CodeIgniter related questions come up.

**Comment by funivan** [comment]
1. https://seld.be/notes/php-versions-stats-2017-1-edition 
2. We can review packages from thephpleague 
3. Found interesting http://period.thephpleague.com/

If you upgrade to 7.0 uses with version 5.5 or 5.6 can use plates, but not latest version. I think this is normal.

**Comment by ragboyjr** [comment]
Not sure i understand:

> If you upgrade to 7.0 uses with version 5.5 or 5.6 can use plates, but not latest version. I think this is normal.

@funivan

**Comment by rogerroelofs** [comment]
I was reading this http://php.net/supported-versions.php which might lend some support to the 7.0 choice.  Even though I have a project that will be stuck on 5.6 for the next year I'm ok with having to use the current version and let the project move on to take advantage of v7 features.

**Comment by ragboyjr** [comment]
@rogerroelofs Good point; however, i don't have any intentions on using any specific 7.0 features, so not sure if there is any pull for me to alienate the 5.x user base.

**Comment by funivan** [comment]
@ragboyjr if you change minimum php to 7.0 it will affect only new versions. 
5.6 got only security bugfixes
7.0 is active supported version

Profit: 
https://github.com/thephpleague/plates/blob/master/src/Template/Func.php#L70

p.s. Users will upgrade faster from 5.6 to 7.0 so this will be small win to all php world.

**Comment by ragboyjr** [comment]
Y, 7.0 would be good. I think i'm on board for using 7, let's do a sample of the other php league packages, and I think that'll help solidify this decision.

**Comment by ragboyjr** [comment]
@funivan ^

**Comment by ragboyjr** [comment]
I've started the 4.0 rewrite, I'm going to go with 7.0 as minimum php version. Currently, i'm not using an 7.0 features in the src and I likely won't for the initial 4.0 release, but my tests are using 7.0 features, so I won't include 5.6 in the CI.
