### ISSUE TITLE
Passing Data to Views to Create Localized Variables

### ISSUE THREAD

**Issue by Knight-Yoshi** [thephpleague/plates#165]
I had a conversation some months ago, with the the guys that develop the MVC framework we use, about passing data from the controller to views that are called from within other views to create localized variables. 

There was a lot of back on the subject and what it came down to was that the controller only knows about the view it's loading and it should not be able to specify variables to be created for views that may or may not be loaded.

Currently that's something that Plates does (which seems ideal), but should the controller that's loading a view be able to tell the View object to create variables for a view that may or may not be loaded? That's also a valid point. However, that also means if you want to pass data to a layout that wraps around the view loaded by the controller, the way they currently handle it is to set the data on an array that can be accessed in any view.

One way I see it is that the controller doesn't know about the views, but the view object/engine does and then creates localized variables. However, should one be able to pass data to the view object like that?

I'm not saying this is bad, I actually like the way Plates handles creating localized variables, but thought I'd get some input from the people that do it.

**Comment by ragboyjr** [comment]
@Knight-Yoshi can you give an example of a rendering a view and telling the view to create variables for a sub view?

All I can think of is something like:

```php
$engine->render('view1', ['var1' => 1, 'var2' => 2]);

// in view1
$this->insert('sub-view', ['var2' => $var2]);
```

**Comment by Knight-Yoshi** [comment]
For instance in the layout view you could render a header view that's a sub-view (nested view might be a better term?). The in the header view you might render a navigation view.

So yeah, your example is accurate.

**Comment by ragboyjr** [comment]
Y, so in my platesphp apps, i use global data for anything that isn't necessary for the controller to load. And i usually use a middleware to inject that data into the plates engine.

So, if we had a site that had navigation loaded from a taxonomy (category tree), we'll need to load the taxonomy from the database and then make sure that the loaded taxonomy is available in every layout.

The best way to implement that would be to:

1. Create a service layer for loading and structuring your taxonomy. This step would have nothing to do with plates.
2. Create a middleware or hook in your application that will use the taxonomy service to fetch the structured data, and in the middleware, add the taxonomy as a global in the plates engine.
3. Then in your layout, when you include the header and nav views, they'll have access to the global data.

Most frameworks should have the ability to utilize middleware on certain routes or groups as well, so you wouldn't need to load the taxonomy on pages that don't need it.

Another approach would be to just inject the taxonomy service as a global into your plates engine, but that could definitely lead to mixing presentation and logic if you aren't careful.

**Comment by ragboyjr** [comment]
@Knight-Yoshi does that make sense?

**Comment by Knight-Yoshi** [comment]
Somewhat. For the first two points I'm not sure what each would consist of (not sure what a service layer or middleware is comprised of), but I get the gist of it. I'm guessing controllers would be part of the middleware then? Which is where the debate with the guys that develop the framework we use comes in. They say that the controllers shouldn't be able to pass data to a view that the controller does not directly load.

So if you load `view1` you can pass data to `view1`, let's say `['username' => 'Knight Yoshi']` and that would create a local variable within that view as `$username`. The same is true if you pass data to the Plates engine for a specific view 
`$templates->addData(['somethingElse' => $someVariable], ['_header']);`
Which would create the local variable `$somethingElse` in the `_header` view. 

However, the debate with them, is that the controller doesn't know about the `_header` view being loaded (if it's even loaded) and as such the controller shouldn't be able to pass data to the view engine that would create a local variable for the `_header` view. Instead you with the way the framework functions now you have to stick the data on an array that's accessible to all views, which if multiple views share the same type of data, but with different values that are loaded within the same page then you have to assign them on different array property names.

So for instance you let's say there's two panels on the page that can be expanded or collapsed.
Instead of
```
$templates->addData(['state' => 'expanded'], ['_panel1']); // can be used only in _panel1
$templates->addData(['state' => 'collapsed'], ['_panel2']); // can be used only in _panel2
```

You have to do
```
$this->view->params['panel1_state'] = 'expanded'; // can be used anywhere
$this->view->params['panel2_state'] = 'collapsed'; // can be used anywhere
```

Personally I like the how Plates handles it, allowing to create local variables. However, like I said their stance on the subject is that `view1` wouldn't know `_panel1` and `_panel2` are loaded within the page. However, as I see it the view object would know and you're just telling the view object to create the variables when/if that view is loaded.

The example above with the panel state as well as navigation are both instances where I found passing data to views not directly loaded by the controller to be a pain.

**Comment by ragboyjr** [comment]
1. By a service layer, i just mean a service class that handles the logic for fetching the data from the db. Similar to like a `CategoryTreeRepository` or something, just a class to fetch the data.
2. The controller would definitely not be apart of the middleware. The point of the middleware is that it should execute before/after the controller action. I was referring to the a middleware that would execute before the controller action and would hydrate the plates engine global state with the navigation view data.

And I think I agree with the developers you mention. Personally, I think your controller actions should just focus on building the view data for the specific view you are creating. Things like widgets/panels/header/navigation are global context to your template layouts and shouldn't require your controller to necessarily know about them.

Technically, the view file you load will see the data loaded for `_panel1` and `_panel2` as in your example, but that's not an issue because you don't need to use them, and you can overwrite them for your view file as well, so it's not really an issue that your view file IMHO.

**Comment by ragboyjr** [comment]
We can reopen this if you feel like this was unresolved.
