### ISSUE TITLE
V4 Documentation

### ISSUE THREAD

**Issue by ragboyjr** [thephpleague/plates#168]
- [ ] Template Shared Data #136
- [ ] Extensions
- [ ] Internal Architecture
- [ ] Trouble Shooting
  - Just create documentation on any of the exceptions and what they mean and how to resolve to help people who get an exception they didn't expect.
- [ ] Advanced Usage
  - Aliasing Funcs
  - Utilizing the __invoke func
  - Overwriting/extending existing funcs
  - Developing your own func
  - Using Props

**Comment by ragboyjr** [comment]
For the docs, i need to build a tool that will take a few branches, build the jekyll site in the `doc` folder and put each built site in folders inside of gh-pages. It should work similar to Couscous where it builds the generated site, the moves it to a temp folder, checks out the gh-pages branch, and then merges/commits the branch.

**Comment by lkraav** [comment]
@ragboyjr what would it take to get the v4 docs going somewhat? Would be useful to understand if v3 docs are enough to get started, or any major confusing differences?

**Comment by lkraav** [comment]
Pardon my ignorance. I overlooked that a nice set of v4 docs are already up on the site definitely seem to be enough to get started. Or maybe it was some usability issue that made it hard to recognize differences after the version dropdown selection in the sidebar.

http://platesphp.com/v4-alpha/engine/framework-integration/ are there any major changes coming here vs v3?

**Comment by ragboyjr** [comment]
@lkraav no worries, I think the main interface won't change much, but I do think I want to re-work some of the internals to be a bit simpler.

**Comment by lkraav** [comment]
> no worries, I think the main interface won't change much, but I do think I want to re-work some of the internals to be a bit simpler.

@ragboyjr what's your workflow? Could we attack this in pair programming mode? Sometimes it takes a more active "together" to get things moving.

**Comment by ragboyjr** [comment]
@lkraav not opposed, but i'm slammed with work prepping for holidays, so we might need to discuss when i'm not so swamped.

**Comment by lkraav** [comment]
I'm not sure at all how and if it's a good idea to use `default_layout_path` parameter at all.

**Comment by ragboyjr** [comment]
`default_layout_path` is my jam. Most of my templates use the same layout file. so instead of adding `$this->layout('layouts/main')` in all of my templates, I can set `'default_layout_path' => 'layouts/main'` and remove the layout directive in the template.

**Comment by butteredptarmigan** [comment]
I think it would be a good idea to follow the widespread trend found on readthedocs and create one page with detailed API documentation, i.e. to document every method automatically, using a tool like phpDocumentor. It would be a great help for nerds and as a quick reference.
