### ISSUE TITLE
Travis-CI failing on 5.3

### ISSUE THREAD

**Issue by carbontwelve** [thephpleague/plates#172]
Travis-CI only supports testing PHP 5.3 on Precise. The `travis.yml` needs updating to correctly set the dist for 5.3,

Personally i'd rather see support for 5.3 stop ;)

```
PHP 5.3 is supported only on Precise.
See https://docs.travis-ci.com/user/reference/trusty#PHP-images on how to test PHP 5.3 on Precise.
Terminating.
```

I opened a PR (#173) containing a single commit that solves this.

**Comment by ragboyjr** [comment]
Let's just drop the 5.3 support, thanks for submitting a PR!

**Comment by physcocode** [comment]
I guess plates is drooping support for 5.3 tests so this issue can be closed i guess
