### ISSUE TITLE
V4 Block Func

### ISSUE THREAD

**Issue by ragboyjr** [thephpleague/plates#175]
Add a block func that will allow the following semantics:

```php
<?php $v->block('section-name') ?>
// define the default block here
<?php $v->end() ?>
```

If the section exists, it should echo the section content and discard the content from the `end` callback. If it does not exist, it should output the contents from the `end` callback.

This maybe depends on #177 

A different alternative is to use an if statement. This is more verbose, but allows us to not even buffer the default content if we don't want to.

```php
<?php if ($v->block('section-name')): ?>
// define the default block content here
<?php endif; ?>
```

In this scenario, the block func simply echos the section content and returns false it exists, or just returns true.

**Comment by ragboyjr** [comment]
- #73 
  - #48

**Comment by ragboyjr** [comment]
Would very much like other opinions on this one to see what the community would prefer.

**Comment by ragboyjr** [comment]
@velosipedist @gmazzap What do you think about this syntax?

**Comment by ragboyjr** [comment]
I'm leaning towards the if block syntax.

**Comment by carbontwelve** [comment]
Not that it carry's much weight but my personal opinion is that the if block syntax makes sense; however I do read `if ($v->block('section-name')):` as `if block with name 'section-name' exists display default text`.

**Comment by ragboyjr** [comment]
Hmm, interesting point. maybe `if (!$v->block('section-name')):`?

@carbontwelve 

I was trying to save on characters, and i was worried people would omit the `!` and end up having both options displayed.

But i'm not sold on either way. Just need feedback from the community to see what makes the most sense.

**Comment by ragboyjr** [comment]
If use the block/end syntax, there would be no ambiguity like you mention; however, we'd have to needlessly process everything in the if block.

**Comment by ragboyjr** [comment]
Maybe we could come up with a way that everything between `block` and `end` is lazily evaluated.

**Comment by ragboyjr** [comment]
I ended up going with just a second parameter to the section func instead of adding a new one. I felt like it was confusing to have two functions that do the same thing, and the if statement part was a little weird.

The new syntax allows a closure to be passed in as the second parameter which is lazily evaluated.

https://github.com/thephpleague/plates/blob/master/test/integration/fixtures/standard/layouts/layout.phtml#L5
