### ISSUE TITLE
V4 Folders Extension

### ISSUE THREAD

**Issue by ragboyjr** [thephpleague/plates#182]
- fallback folders (search one folder, then another if not there) #59
- folders (find template in folder like admin::main)

**Comment by lkraav** [comment]
@ragboyjr curious, why isn't it possible to add an array of folders during engine configuration?

Would be better DX if upstream did `foreach` dance :)

**Comment by ragboyjr** [comment]
@lkraav an array is the canonical form of the base_dir, if you pass in a string, it converts it into an array :)
