### ISSUE TITLE
V4 Alpha

### ISSUE THREAD

**Issue by ragboyjr** [thephpleague/plates#196]
- [x] Start initial documentation
- [x] Setup a system similar to thephpleague/period where the documentation shows v3 and v4 docs.
- [x] Figure out an EOL for v3 #206 
- [x] Branch master into v3 branch
- [x] Merge 4.0-dev to master
- [x] Tag 4.0-alpha release

**Comment by awhillas** [comment]
any ETA on 4.0-alpha availability?

**Comment by ragboyjr** [comment]
Hopefully sooner than later, the main thing holding up alpha is getting the documentation setup so that we can switch between v3 and v4-alpha docs similar to like the laravel docs or symfony's api docs.

I made a note here for what I'm looking to do: https://github.com/thephpleague/plates/issues/168#issuecomment-358573085

**Comment by ragboyjr** [comment]
For what it's worth, i've been using `"league/plates": "dev-v4.0-dev"` in my composer.json to do some initial testing in my own projects and it's been working fairly well. Would definitely appreciate more real world testing from the community.

**Comment by ragboyjr** [comment]
@awhillas alpha has been tagged (a few weeks ago).
