### ISSUE TITLE
Better IDE Support

### ISSUE THREAD

**Issue by ragboyjr** [thephpleague/plates#222]
I've recently started using PHPStorm and one of the main annoyances in using plates is that there isn't any easy IDE support for showing the existing variables or what their types are.

I think something similar to magento2 where you have one block variable which handles all of the interaction might be a good solution. Will need to think it through on how it would best work with 4.0.

**Comment by ragboyjr** [comment]
Maybe we could change `$data` in the template from being an array to also accept mixed or something?

Then we could do:

```
/** @var SomeViewModel */
$vm = $v->data
```

**Comment by ragboyjr** [comment]
Another aspect that could use better IDE completion is the Engine Methods, would be great if that could somehow provide better IDE help as well.

**Comment by ragboyjr** [comment]
And another are render context methods. Maybe something like what php-di does would suffice:

http://php-di.org/doc/ide-integration.html

**Comment by lkraav** [comment]
Hi @ragboyjr. I'm trying to find a solution for how to make PhpStorm understand `$v->insert()` method inside a template, and not flag it as "not found".

Do you have any further thoughts on the subject here?

https://stackoverflow.com/questions/15634021/how-to-document-magic-call-and-callstatic-methods-for-ides?noredirect=1&lq=1 seems to be the most popular question on the subject, but I'm not sure how exactly to apply it.

Maybe https://docs.phpdoc.org/references/phpdoc/tags/method.html but how exactly?

PhpStorm stubs https://www.jetbrains.com/help/phpstorm/ide-advanced-metadata.html

EDIT Can't override a class method in 2019.1? https://youtrack.jetbrains.com/issue/WI-41053

**Comment by ragboyjr** [comment]
@lkraav thanks for looking at this, part of me wonders if maybe we do something like: https://github.com/netz98/n98-magerun/blob/master/src/N98/Magento/Command/Developer/Ide/PhpStorm/MetaCommand.php

where we just have a tool that you can run and generate phpstorm meta output for the IDE.

**Comment by lkraav** [comment]
@ragboyjr nice find!

Are you able to put a bare skeleton of such a generator together, maybe for just one method like `insert()`? Looking at `MetaCommand.php`, getting started might be a bit over my head, but I think I could stoke a small pre-started fire further.

AFAICT `$STATIC_METHOD_TYPES` has been deprecated for a while, already? Not sure what has to be adjusted. I wonder if need to find JetBrains Slack from somewhere and ask those deeper in the know.

https://stackoverflow.com/questions/39398021/intellij-idea-slack-user-channel apparently they're on Discord https://discord.gg/ysd6M4r

**Comment by lkraav** [comment]
On Discord, Daniele from JetBrains recommended looking at https://github.com/King2500/symfony-phpstorm-meta

**Comment by odan** [comment]
The IDE Helper plugin for CakePHP supports automatic collection of view template variables from (PHP) files:

https://github.com/dereuromark/cakephp-ide-helper/releases/tag/0.13.19?fbclid=IwAR0KuINb6808_ZZcr_YPLD1hnr30ZC5SDW3TTWaOwhRbnA30pBsmrC6BUzw

Maybe their concept / solution could also be helpful for Plates.

**Comment by ragboyjr** [comment]
I think the solution around this is moving to a new (optional) component model that is IDE friendly by design instead of mucking around with PHPStorm meta helpers.
