### ISSUE TITLE
why Data sharing across templates , is security vulnerability. ?!!

### ISSUE THREAD

**Issue by kadevland** [thephpleague/plates#224]
I think that sharing the data between template is a security vulnerability.
i think add like new feature or  not default feature.
exemple : 
$v->insert('...')->withContextData() / withData() / withParentData ...

**Comment by ragboyjr** [comment]
@kadevland in v4-alpha, you can turn off data sharing by setting the config value `merge_parent_data` to false.

**Comment by kadevland** [comment]
ok.
may be add the posibilite for insert  take parent data when config merge_parent_data is false

**Comment by ragboyjr** [comment]
You could do that by simply passing in the data like:

```php
$v->insert('template', $v->data());
```
