### ISSUE TITLE
set and get dynamic data array

### ISSUE THREAD

**Issue by S3lfC0d3r** [thephpleague/plates#226]
My validate login form print this array:
```
Array
(
    [0] => The Customer Name field is required
    [1] => The Customer Password field is required
    [2] => The Email field is required
    [3] => The Gender field is required
    [4] => The Credit Card field is required
)
```
how do can i send data to `login/index` using `addData` method like this:

```
    $this->templates->addData([`??` ], 'login/index');
```
and get in login index?!

Thanks for any help

**Comment by napec** [comment]
```php
$errors = [
    'The Customer Name field is required',
    'The Customer Password field is required',
    // ....
];

** @var \League\Plates\Engine $engine */
$engine->addData(['errors' => $errors], 'login/index');
// or...
$engine->render('login/index', ['errors' => $errors]);
```

...in your [path_to_templates]/login/index.php
```php
<?php foreach ($errors as $error): ?>
    <?=$error ?><br>
<?php endforeach ?>
```

**Comment by ragboyjr** [comment]
@napec Thank you for your response. @S3lfC0d3r @napec's response is precisely the way to go about this.

If you have any other issues let me know, otherwise, i'll close this issue. Thanks!

**Comment by S3lfC0d3r** [comment]
@napec @ragboyjr Sorry For Delay I'm So busy. 
@napec I think your method good work but not complete:
with your method i need to style error(ie: bootstrap danger alert into div) before template then send array to template and print. in action i need to print each error into div in template not in my code(ie: controller Or Class).

**Comment by S3lfC0d3r** [comment]
@napec @ragboyjr Sorry For delay Im so Busy..

Thanks @napec Good Work.
