### ISSUE TITLE
Support for multi level menus

### ISSUE THREAD

**Issue by filips123** [thephpleague/plates#228]
I want to make multi level menu, with any depth. How can I make it?
In Twig, there are macros. Is something like that available in Plates?

See https://stackoverflow.com/questions/45955614/multi-level-menu-with-twig for Twig solution.

**Comment by ragboyjr** [comment]
@filips123 Y, I think in both twig and plates, just make a include/component template would be more than fine.


```html
<header>
  <nav><?=$v->insert('nav-list-items', ['navTree' => $navTree])?></nav>
</header>
```

```html
<ul>
  <?php foreach ($navTree->children as $navNode): ?>
    <li>
        <?=$navNode->getName()?>
        <?php if ($navNode->children): ?>
            <?php $v->insert('nav-list-items', ['navTree' => $navNode])
        <?php endif; ?>
    </li>
  <?php endforeach; ?>
</ul>
```

**Comment by filips123** [comment]
How exactly should i make component template? Could main and component template be in same file?
This should probably be in the documentation of Plates.

**Comment by ragboyjr** [comment]
it's just a normal template that can be included.
