### ISSUE TITLE
Naming convention for template names

### ISSUE THREAD

**Issue by filips123** [thephpleague/plates#230]
Which naming convention should be used for template names? Should it be `snake_case`, `camelCase`, `PascalCase` or something else?
This should be specified in [documentation of syntax](http://platesphp.com/v3/templates/syntax/).

**Comment by ragboyjr** [comment]
I typically do `dash-case`, but you can do whatever you want.

**Comment by filips123** [comment]
OK. Thanks for answer!
Maybe you could add this to documentation of syntax.

**Comment by ragboyjr** [comment]
Personally, I don't have plans on adding that to the documentation, but I would accept a PR on that.
