### ISSUE TITLE
4.0: Render context variable name should be explicit `$view`, rather than implicit `$v`

### ISSUE THREAD

**Issue by lkraav** [thephpleague/plates#232]
Various reasons

1. Better DX, via https://miguelgfierro.com/blog/2018/python-pro-tips-understanding-explicit-is-better-than-implicit/ etc

2. Most PHPCS implementations, PHPMD, and possibly others, will highly likely flag single-letter variables (or anything less than 3 characters) as bad practice. They are probably correct.

3. ...

**Comment by ragboyjr** [comment]
`$v` was for keeping the key strokes down, but pretty sure this is configurable already with: 

```php
$plates->addConfig(['render_context_var_name' => 'view']);
```

**Comment by lkraav** [comment]
It is configurable, and I did. But decisions (better defaults), not options, maybe? :)

**Comment by ragboyjr** [comment]
I think this is a moot point now that I'm scraping v4, so we'll just be using $this for the templates, and the new component system will also use this or captured variables from a closure. In both scenarios, it's going to be more explicit and type friendly which I think addresses the main concern here.
