### ISSUE TITLE
confused about nesting templates

### ISSUE THREAD

**Issue by jorygun** [thephpleague/plates#233]
I'm trying to do this:
Link an array of data in my controller to a partial template ... a table displaying the data.
Render a full template which contains the partial template with its data. 

Should the controller do a make('partial.tmp',data_array)?  Then how do I get the partial into the full template with its data? I've been trying insert, but I don't know how to get the data from the full template into the partial template.  Or does the controller send data to the partial template?.  Stuck.   

```
--------------
profile.tpl

   $this->layout('layout.main', $layout_data) ;
   ?>
   ... stuff..
   <?php insert('profile.div'); ?>  // or should be fetch?  

--------------
profile.div template
    <div>
  <h1> <?=$username ?> Profile</h1>
  (lots more vars)
  </div>

--------------
view:
   $template_data = array ( ... lots of var=>val ... );
   
   $template = $this->templates->make('divs/profile.div',$template_data);
  #$profile_div =  $this -> templates->render('divs/profile.div', $template_data);
     echo $this->templates->render('profile.tpl');

```

**Comment by ragboyjr** [comment]
Closing as this is stale.
