### ISSUE TITLE
folder fallback not working as expected for "theming" render/layout

### ISSUE THREAD

**Issue by fkooman** [thephpleague/plates#234]
I followed the [Simple example](http://platesphp.com/v3/simple-example/) and tried to add "theming" from the [Folders](http://platesphp.com/v3/engine/folders/) documentation.

It makes the most sense to add `template.php` to the `theme1` folder to point to a different CSS file.

```
$templates->addFolder('theme1', '/path/to/theme/1', true);
echo $templates->render('theme1::profile', ['name' => 'Jonathan']);
```

However, this does _not_ work. It will try to locate `profile.php` in the `/path/to/theme/1`, which fails, so it falls back to the default path where it finds `profile.php`. However, `profile.php` contains this call:

```
<?php $this->layout('template', ['title' => 'User Profile']) ?>
```

This again takes the "default" `template.php` instead of the one from `theme1`. I'd also have to modify the call the `layout` to point to `theme1::template` which then does work... But then it is not easily configurable from your controller... 

So it seems the only way to make this work is to create a "full" theme, i.e. copy all templates in the directory of the theme, except the ones that do not reference other templates... So here I'd need to copy `profile.php` to the `theme1` folder as well, even though only the `layout` call would be different...

Is there any other way to make this easier without needing to duplicate templates you don't want to modify in your theme?

**Comment by ragboyjr** [comment]
@fkooman this is a great discovery. I think this might do well with a proper theme extension that would allow you to set a theme variable for plates and it'll be used as context when fetching products.

So, implicitly ever call to a template file would check for the currently set theme and fallback accordingly.

**Comment by fkooman** [comment]
How would one go about this? I've been looking at it for a few hours now and I don't really understand how to override the calls to "render" and "layout" from an extension to make it consider the "theme" path... 

My approach was to try and call setDirectory from the extension to the theme path if the template exists in the theme directory, otherwise do nothing...

**Comment by fkooman** [comment]
It turns out it is not _that_ difficult to write a more or less compatible Plates implementation that does work with "themes", i.e. allows you to specify a list of folders where it starts looking in the first one and 'falls back' to the later ones...

https://gist.github.com/fkooman/6942065e6dd3ad2c540349f3e6dba6f6

**Comment by ragboyjr** [comment]
Good deaal @fkooman will check this out when I get bit more time. Little slammed during holidays

**Comment by ragboyjr** [comment]
When I think this through, I wonder if the component system will better tackle this type of issue. I'm going to attach this to the 3.5 milestone for now and see if this something that we can look at then.

**Comment by ragboyjr** [comment]
Theme support has been merged to master!
