### ISSUE TITLE
Is it possible to add build() function like render() ?

### ISSUE THREAD

**Issue by eguvenc** [thephpleague/plates#237]
`<?php
// -------------------------------------------------------------------
// Welcome.phtml
// -------------------------------------------------------------------
//
$template->layout('_Template.phtml',
	[
		'title' => 'Welcome',
		'header' => $template->fetch('Parts/_HeaderNavbar.phtml')
	]
);
$html = '&lt;p&gt;Some html content..&lt;/p&gt;';

$html = $template->build($html);
return new Zend\Diactoros\Response\HtmlResponse($html);`

Is it possible to add build() function like render() ?

**Comment by ragboyjr** [comment]
It's unclear from this feature request what you're specifically asking for.
