### ISSUE TITLE
'escape_encoding' cofiguration not working

### ISSUE THREAD

**Issue by david-chaves** [thephpleague/plates#242]
Hi I'm using the plates latest dev-master code with composer and I'm trying to change the option to make it work with the ISO-8859-1 charset (I know, but is an old production server and it will not change the charset :| ), but still renders the characters incorrectly:

```php
$engine = League\Plates\Engine::create('./templates');
 $engine->addConfig(['escape_encoding' => 'ISO-8859-1']);
```

and on my .phtml template the headers:

```html
<meta http-equiv="Content-Type" content="text/html">
<meta charset="iso-8859-1">
```

and I'm trying to render the template like this:
```php
echo $engine->render("response", ['labelTransaccion' => 'Resultado de la transacción']);
```

However, I'm getting this result: 
![label](https://user-images.githubusercontent.com/16734552/61162982-fb6eb480-a4d0-11e9-8ac1-79712520d25f.png)

What I'm doing wrong?

**Comment by ragboyjr** [comment]
Thanks @david-chaves i'll take a look at this and get back to you.

**Comment by david-chaves** [comment]
I forgot to to add the template code too:

```html
<td>
       <span class="data-label-txt"><?= $v($labelTransaccion) ?></span>
</td>
```

**Comment by david-chaves** [comment]
Hi, any updates on this?

**Comment by ragboyjr** [comment]
@david-chaves I'm no longer working on the v4 alpha as is, it might be best to use v3 for now.
