### ISSUE TITLE
Correct way for loading assets

### ISSUE THREAD

**Issue by realrecordzLab** [thephpleague/plates#243]
I'm reading the documentation, but i've not clear how to load all my assets files. I've noticed that if I set the correct path for my css and js files, they will not be loaded.

here is my code. Any suggestion and explaination will be appreciated.

``` 
define('ROOT', __DIR__); // this constant is defined inside my front controller
// this is how I'm loading the asset method inside the controller class
$this->view = new \League\Plates\Engine( ROOT.'/assets/templates' );
$this->view->loadExtension(new \League\Plates\Extension\Asset( ROOT, true));
```

view file
```
<link rel="stylesheet" href="<?php echo $this->asset(/assets/css/bootstrap.min.css); ?>" type="text/css">
```
I've got this error:
>> /assets/css/bootstrap.min.1545385632.css - No such file or directory

**Comment by Dexarys** [comment]
Hello, 
I have the same error as you..
The Engine finds my file but not the navigator. Have you found a solution ?
