### ISSUE TITLE
Passing Array To Template

### ISSUE THREAD

**Issue by cherokeelakes** [thephpleague/plates#249]
Is it possible to pass an array to a template? I do not see anything in the documentation about this, but I tried:

`$apps = array(1, 23, 'CRM', 'fasdff');
echo $this->template->render($view, ['apps' => $apps]);`

This works, just not when the variable passed is an array.

**Comment by lkraav** [comment]
It definitely works, we're passing massive data arrays into templates no problem.

**Comment by asvvvad** [comment]
doesn't work in v4.0

**Comment by asvvvad** [comment]
It seems to be a problem with auto-escaping? It expects all data to be a string:
```
PHP message: PHP Warning:  htmlspecialchars() expects parameter 1 to be string, array given in league/plates/src/Extension/RenderContext/func.php on line 114
```

Is there anything to do here? It seems we have to rewrite the templates and downgrade to v3
