### ISSUE TITLE
Call $next with original $args instead of returning

### ISSUE THREAD

**Issue by JoyceBabu** [thephpleague/plates#252]
I was just going through the v4 implementation, and I have a doubt. If `foldersResolvePath` was unable to resolve the path, shouldn't it call `$next` with the original arguments, rather than failing?

For example, consider the following example

```php
<?php
$templates = new League\Plates\Engine::create('/path/to/templates', 'php');
$templates->register(new MyCustomExtension());
$templates->addFolder('test', '/var/www/html/templates');
$templates->render('test::abc');
```

What if `MyCustomExtension` is capable of resolving `test::abc`? Currently it is called only with the path, `/var/www/html/templates/abc`. Since `Folders` extension was unable to resolve the path, it should try calling `$next` with `test::abc` before failing.

https://github.com/thephpleague/plates/blob/14056d709e1de76a93813b07eed1c3c86fbb5fcb/src/Extension/Folders/folders.php#L8-L34

**Comment by ragboyjr** [comment]
Thanks for the concern @JoyceBabu I'm abandoning v4 as is, so this won't be addressed.
