### ISSUE TITLE
section is not included when added via the insert

### ISSUE THREAD

**Issue by MarksEliel** [thephpleague/plates#254]
when I insert a content after I call the section the content is not rendered in the section above the insert:

print1: https://i.imgur.com/GQ4aIUi.png
print2: https://i.imgur.com/3aF5aYL.png

**Comment by ragboyjr** [comment]
@MarksEliel what version are you using? Can you also include a minimum example highlighting the bug?

**Comment by fwerner13** [comment]
I'm having a similar problem (using version 3.3): 

Layout: 

```php
<!DOCTYPE html>
<html lang="de">
<head>
</head>
<body>
    <?= $this->section('header') ?>

    <main class="content">
        <?= $this->section('content') ?>
    </main>
</body>
</html>
```

Template: 

```php
<?php 
	$this->layout('layouts/main');
?>

<?= $this->fetch('parts/header'); ?>
```

parts/header.php: 

```php
<?php $this->start('header') ?>
    test
<?php $this->stop() ?>
```

This will not render "test" in the main layout. 

@MarksEliel: My workaround for the moment is using the start()/stop() methods in the main template: 

```php
<?php 
	$this->layout('layouts/main');
?>
<?php $this->start('header') ?>
    <?= $this->fetch('parts/header'); ?>
<?php $this->stop() ?>
```

**Comment by ragboyjr** [comment]
I think this makes sense, it'd be helpful if you could provide a PR with a broken test to cover this scenario and we can go from there.
