### ISSUE TITLE
Template not completely rendered if passed string is over 300k chars long

### ISSUE THREAD

**Issue by Cylop** [thephpleague/plates#255]
I'm trying to create a template that displays some "huge" tables with around 400 rows each.  But apparently  it only renders 300 Rows of the first table and after that nothing else. I tried to go through that array with a foreach loop but i threw the idea away and inserted the html table string directly into the template. (Table is generated via simple php class)

Here's the snippet:  (for my first approach)

`
<?php if($transaction_actions): ?>
            <h3>Transactions Data</h3>
            <h6><small class="text-muted">Tick the boxes which entries should be created</small></h6>
            <div class="row">
                <div class="col">
                    <table class="table table-responsive table-hover thead-dark">
                        <tr>
                            <th>Approve</th>
                            <?php foreach($transaction_fields as $headline): ?>
                                <?= ($headline[1] == null ? '' : '<th>' . $headline[0] . '</th>')?>
                            <?php endforeach ?>
                        </tr>
                        <?php foreach ($transaction_actions['create'] as $k => $row): ?>
                            <tr>
                                <td><input type="checkbox" name="create_payment[]" value="<?= $k ?>" checked> </td>
                                <?php foreach ($row as $field): ?>
                                    <td><?= $this->e($field) ?></td>
                                <?php endforeach ?>
                            </tr>
                        <?php endforeach  ?>
                    </table>
                </div>
            </div>
        <?php endif?>
`

The data stored in `$transaction_actions['create']`. is 300k+ chars long. 
The button after that nor the footer is getting rendered. 

Tried the same thing with providing the assembled table as string and echoing it. Same result.  Heres the code: 
`<?= $partner_table_generator->createTable('create') ?>`

Maybe it's my fault but i don't know what i should change to get it to work. 

Timeout of php is set to 0 and memory to 512mb

**Comment by rogerroelofs** [comment]
Have you checked your error log for messages?  Every time this has happened to me it's either been out of memory or unexpected data my code wasn't prepared for.

**Comment by Cylop** [comment]
Yeah already checked that, no error no out of memory. Its working perfectly fine if i just echo it out in php but thats not the way i want to use it

**Comment by rogerroelofs** [comment]
What version of plates are you using?  What charset is the data you are trying to escape?  Are you setting escape_encoding anywhere?

**Comment by Cylop** [comment]
I am currently using plates version 3.3 and the charset is UTF-8. It's 20 columns wide and 400+- rows in total for this one table. 
Just tried to create a DOMDocument and pass that but same result. 

Edit: 
I just updated to plates v4-alpha and it seems like its working. Only got some stack traces on top, maybe i can fix that too. I'll give an update to you

Edit2:  
Got rid of those errors and suddenly it stopped working again. I mean it's now displaying 50 more rows but footer and button is missing.

**Comment by Cylop** [comment]
Got it working on my vm and its working fine. Dont know what was the problem, maybe memory issue. Thanks for your help!
