### ISSUE TITLE
Multi folder fallbacks example?

### ISSUE THREAD

**Issue by mhf-ir** [thephpleague/plates#256]
In this example:
https://platesphp.com/v4-alpha/simple-example/
how can I add multiple folder for fetch if not exist try next folder.
```php
<?php
$templates = League\Plates\Engine::create('/path/to/templates');
```

```php
<?php
$templates = League\Plates\Engine::create(['/path/to/overwrite', '/path/to/templates']);
```

so:
```php
<?php

echo $templates->render('profile', ['name' => 'Jonathan']);
// if profile.phtml exist on /path/to/overwrite render then try '/path/to/templates' then return error

**Comment by ragboyjr** [comment]
@mhf-ir sorry for the late reply,

curious, what exactly is the use case behind this?

You can use the addFolder method on the engine that is registered to support this which will accept an array of prefixes/locations to search for that specific folder.

**Comment by mhf-ir** [comment]
Design framework/web app that has default layout system with default layout system. It's composer/packagist package.
If developer want to change it dont change the `vendor/myframework/default-layout-path/layout.phtml` it's add new directory if file exist read from src or lib directory instead of vendord default path. If not exist okey use vendor default file.

**Comment by ragboyjr** [comment]
I'm going to be scrapping the v4 alpha on this. I won't be removing the alpha tag, but future releases won't be off of the alpha, it's going to be abandoned as is. Will be making a roadmap for the future of plates.
