### ISSUE TITLE
Php 8 compatibility

### ISSUE THREAD

**Issue by roxblnfk** [thephpleague/plates#257]
Could you update the code of the stable version of the template engine for compatibility with php 8 and composer 2?

**Comment by ghost** [comment]
I had to add `--ignore-platform-reqs` to install for now

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires league/plates ^3.3 -> satisfiable by league/plates[3.3.0].
    - league/plates 3.3.0 requires php ^5.3 | ^7.0 -> your php version (8.0.0) does not satisfy that requirement.

```

**Comment by DerKnerd** [comment]
If you want to stick with Plates 3.x you probably won't get PHP 8.0 support. The 4.0 version seems to change some things how the templating works. If you want to stick with the Version 3.x patterns you can install my fork 🙂 

Here is the composer package: https://packagist.org/packages/jinya/plates Apart from that, I decided to drop the support for PHP pre 8.0 and added all new features introduced in PHP 8.0. I intend to keep the version 3.x style of templates.

@ragboyjr I hope it is ok, that I mention my fork here, if not just tell me or delete the comment 🙂

**Comment by ragboyjr** [comment]
No worries @DerKnerd, and I'll be upgrading the v4 branch to support php8.

**Comment by roxblnfk** [comment]
@ragboyjr could you also add a tag for version 3?
