### ISSUE TITLE
Replace 'callback' type with 'callable' in PhpDoc

### ISSUE THREAD

**Issue by vixducis** [thephpleague/plates#284]
Currently, the 'callback' type is being used in the PhpDoc of 2 files:
- src/Template/Functions.php
- src/Engine.php

Can we maybe replace this with the 'callable' type, as this the more or less 'official' type? A lot of static code analysis tools will not recognise 'callback', but 'callable' works fine.

**Comment by ragboyjr** [comment]
Ya that sounds fine, feel free to submit a pr
