### ISSUE TITLE
Release 3.5 with PHP 8.2 compatibility and theme support?

### ISSUE THREAD

**Issue by Rayne** [thephpleague/plates#300]
I'm currently deciding for a new project whether I stick with native PHP templates wrapped by a customized `View` from [Fat-Free Framework](http://fatfreeframework.com) or try out Plates. For that reason, I studied the commit log, pull requests and the issue tracker.

According to [the page listing commits after release 3.4](https://github.com/thephpleague/plates/compare/v3.4.0...v3) (from Dec 25, 2020), meaningful changes are already part of the `v3` branch that are not released. Is there a specific reason why the following features and fixes are not published with a proper release?

- PHP 8.1 (and probably 8.2) compatibility
  - #297
- Theme support
  - #270

A release would also close these issues:

- PHP 8.1 (and probably 8.2 compatibility)
  - #296
- Theme support
  - #283
  - #292

I second the proposal by @luri-fr, that the components support mentioned in #267 should be moved to a later release to provide a proper release for current PHP versions.

In my opinion, the next release should also solve #293. As far as I understood the issue, `make()` has only to call the `data()` function when an additional argument is specified.

**Comment by Rayne** [comment]
@ragboyjr @reinink How can we users help creating a new release?

**Comment by ragboyjr** [comment]
Thanks for this feedback, will take a look at this over the weekend.
