### ISSUE TITLE
addData to all templates in a directory

### ISSUE THREAD

**Issue by jk3us** [thephpleague/plates#31]
This is just a nice-to-have request... But it would be useful for me to be able to `addData()` to all templates in a defined directory... something like 

```
$templates->addFolder('admin', '/path/to/admin/templates');
$templates->addData(['admin_value'=>$admin_value], 'admin::*');
```

So `$admin_value` would be available to any template in that directory, but not others.

**Comment by ragboyjr** [comment]
I like this feature and will include it for 4.0, but will need to work on the syntax a bit.

**Comment by ragboyjr** [comment]
Closing in favor of #171
