### ISSUE TITLE
The section name "content" is reserved

### ISSUE THREAD

**Issue by moazam1** [thephpleague/plates#43]
I copied and pasted an example from your this link http://platesphp.com/templates/inheritance/ and got following exception:

 'The section name "content" is reserved.'

In Template.php file on line 171 you have reserved content name. Can you please update your docs to reflect this change?

I have two questions as well:
1. What's the difference between fetch and insert function?
2. Let's say I setup a folder admin. Now I want to insert template blocks from a folder that resides in the admin directory i.e. admin/partials. Is it possible to use $this->fetch('partials/navigation') instead of $this->fetch('admin::partials/navigation')

**Comment by ivorobioff** [comment]
@reinink  Please update the official documentation as well http://platesphp.com/templates/layouts/
