### ISSUE TITLE
"Deep" template inheritance

### ISSUE THREAD

**Issue by gmazzap** [thephpleague/plates#47]
Currently, template files can override layout sections only one level deep: included templates (partials) can define sections, but they are not overridable from "main" templates.

Assuming this layout:

``` php
<?= $this->fetch('header.php') ?>

<body>
...
</body>

<?= $this->fetch('footer.php') ?>
```

And following `header.php`

``` php
<html>
<head>

<?php if ( $this->section('styles') ) : ?>
    <?= $this->section('styles') ?>
<?php else: ?>
    <style src="path/to/default/css.css">
<?php endif ?>

</head>
```

The section `"styles"` **can't** be overridden from a template that uses the layout, because when layout includes the partial it creates another template object that is not aware of _parent_ template sections.

In my fork, I added [this commit](https://github.com/Giuseppe-Mazzapica/plates/commit/23e968da14378c9f788cc50d5afa43dec9aaa116), that, by passing parent template sections to included template objects, allows "deep" inheritance (i.e. inheritance for partials) as seen in Twig and other non-php engines.

If you like it I can write unit test and submit a PR.

**Edit**
The linked commit has a bug, because template `render()` method doesn't take name. Fixed [here](https://github.com/Giuseppe-Mazzapica/plates/commit/aeba2441f06b88f6fc61631dbcebc17f6001f771).

**Comment by ragboyjr** [comment]
Closing in favor of #169! Thanks
