### ISSUE TITLE
Less verbose section override?

### ISSUE THREAD

**Issue by gmazzap** [thephpleague/plates#48]
Currently, to define multiline default section content one needs an `if` / `else` block.

From your docs:

``` php
<?php if ($this->section('sidebar')) : ?>
        <?= $this->section('sidebar') ?>
<?php else: ?>
        <ul>
            <li><a href="/link">Example Link</a></li>
            <li><a href="/link">Example Link</a></li>
        </ul>
<?php endif ?>
```

In my fork, with [this commit](https://github.com/Giuseppe-Mazzapica/plates/commit/cbc105b2484be95cef931020f21bddcc31148955) I added `hasSection()` template method that makes same thing doable using only an `if` statement, for less verbose and more readable templates.

Example:

``` php
<?php if ( ! $this->hasSection('sidebar')) : ?>
        <ul>
            <li><a href="/link">Example Link</a></li>
            <li><a href="/link">Example Link</a></li>
        </ul>
<?php endif ?>
```

If you like it I can write unit test and submit a PR.

**Comment by ragboyjr** [comment]
Closing in favor #169.
