### ISSUE TITLE
Extensions Repository

### ISSUE THREAD

**Issue by RobinDev** [thephpleague/plates#54]
Hello,

I suggest to add a `Extension.md` file to index the open source extensions developped by communauty.

I can suggest a pull-request if the idea seems pertinent.

Good week.

**Comment by snsmurf** [comment]
I've just released, what i've labeled "Advanced Assets". I wanted, for a project the ability to have assets run in a similar way to templates with the fallback ability but without releasing the full theme folder URLs or having PHP process them.
Works by symlinking the found assets to a more web accessible directory so the browser can still process rather then having PHP do it or having the ugly urls.
So it could take an asset from example.com/themes/my-sites-theme/assets/css/site.css and symlink it to example.com/assets/css/site.css.

https://github.com/snscripts/advanced-assets

Hopefully the readme covers everything, was also a project for me to learn unit testing, something i've been meaning to do for the past 6 / 7 years, so hopefully the tests are decent! Aside from the two methods that deal with symlinking (afte research, seems there's no real way to unit test symlinks), every other method should be covered!

Feedback would be much appreciated, not just on the package, but the unit tests as well given it was my first attempt.

**Comment by odahcam** [comment]
Why there's no Extensions.md yet? 😯

**Comment by ragboyjr** [comment]
Anyone care to submit a PR for this?

**Comment by odahcam** [comment]
Pull #162
