### ISSUE TITLE
simple example and others broken

### ISSUE THREAD

**Issue by mindyk** [thephpleague/plates#62]
many examples assume that the Engine object has a render method, whish is not the case (any more?)

**Comment by Giuseppe-Mazzapica** [comment]
@mindyk [Engine **has** a `render()` method](https://github.com/thephpleague/plates/blob/master/src/Engine.php#L275-278)

**Comment by reinink** [comment]
Yep, @Giuseppe-Mazzapica is correct, the Engine and Template classes both have `render()` methods.

**Comment by mindyk** [comment]
my bad , i had the 2.* version. Sry to have bothered you
