### ISSUE TITLE
Asset extension not returning correct path for files

### ISSUE THREAD

**Issue by andrewying** [thephpleague/plates#64]
I am not entirely sure whether it's just me not being familiar to how Plate works or if this is actually a bug so please do bear with me.

This issue occurs where I have a file structure like below:
/home/user/domain/public_html/ (web root)
-> assets/
---> css/
-----> stylesheet.css
---> js/
-----> script.js

So in this case the extension would be loaded as follows:
```
$engine->loadExtension(new League\Plates\Extension\Asset('/home/user/domain/public_html/assets'));
```
And when we are trying to load say stylesheet.css in a template using this code:
```
$this->assets('css/stylesheet.css');
```
the code would return css/stylesheet.css?v=(something) instead of assets/css/stylesheet.css?v=(something).

Anyone have any idea if there's something I've done that's wrong or if this is indeed a bug?

**Comment by reinink** [comment]
I'm not sure I'm following you 100%, but basically you need to link to your public assets in the same way you would if you were not using the asset extension. So if your CSS and JavaScript files are in an `assets` folder, you need to link to that folder, like this:

``` php
$this->assets('/assets/css/stylesheet.css');
```

However, that does have implications for the path you define when instantiating the asset extension. In your situation you would then do this:

``` php
$engine->loadExtension(new League\Plates\Extension\Asset('/home/user/domain/public_html'));
```

Plates must know where the files are actually saved on the disk so it can determine the time of last edit. It does this by combining the path you provide to the asset extension with the path you set in your actual templates. So, again, in your case it would be:

`'/home/user/domain/public_html'` + `'/assets/css/stylesheet.css'`

I hope that makes sense!

**Comment by robertmain** [comment]
Not to bump an old issue, but I'm having this problem right now...

If I set (in my controller):

```php
$platesInstance->loadExtension(new Asset('path/to/my/assets'));
```

And then call

```php
<?= $this->asset('img/logo.png'); ?>
```
in my view..

the output is:

`img/logo.png?v=1570911993`, whereas I would've expected it to be `path/to/my/assets/img/logo.png?v=1570911993`
