### ISSUE TITLE
HHVM support

### ISSUE THREAD

**Issue by philsturgeon** [thephpleague/plates#65]
Could we take hhvm out of the allowed failures and see how well it does? Things are a bit more stable over there now so it would be good to see how this works.

**Comment by lalop** [comment]
I will be really interested to help on this point

**Comment by reinink** [comment]
As far as I can remember it does very well. However, the [mikey179/vfsStream](https://github.com/mikey179/vfsStream) requirement (used in the tests) doesn't do well on HHVM, so some tests fail. It's possible, however, that that library now supports HHVM, which would make this switch painless. I'll give it a try!

**Comment by reinink** [comment]
So Plates still works fine on HHVM from what I can tell, but vfsStream does not. I'm not really prepared to move away from using vfsStream in the tests, so we can either leave the HHVM tests failing, or simply remove the tests for them. I'm thinking I'll do the later. If folks want to use Plates on HHVM, they totally still can.
