### ISSUE TITLE
testCachedAssetUrl fails out of the box, windows 7

### ISSUE THREAD

**Issue by chrismichaels84** [thephpleague/plates#72]
A fresh clone of the repo throws 7 failed tests. Six of them are discussed in #71.

The seventh test is not due to directory separators.

Here is my failure.

```
2) League\Plates\Extension\AssetTest::testCachedAssetUrl
Failed asserting that false is true.

C:\wamp\www\chrismichaels84\plates\tests\Extension\AssetTest.php:40
```

**Comment by reinink** [comment]
Same as #71, I'm going to close this for now until we have a way to run our tests on Windows. At this point I don't think anything is actually broken with the library, just the tests.
