### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by patkruk** [thephpleague/plates#74]
Hey, can you bump the version number? Thanks!

**Comment by ragboyjr** [comment]
@patkruk is this still an issue?

**Comment by patkruk** [comment]
@ragboyjr Looks like the latest tag (3.1.1) is way behind the master branch, so it would be nice to have it updated.

**Comment by ragboyjr** [comment]
@reinink what do you think about a 3.2 or maybe 3.1.2 release in the meantime? Master has several minor documentation fixes, but there are a few other PR's that we could do to fix some existing functionality as well.

BC Fixes

#133 #132 #126 #124 #110 #86

BC Feature

#122 #111 #77 #68 #67 #66 

I'm pretty sure if we just accept the fixes we can do a patch release. If we do features/patches, then we'll bump to 3.2.

**Comment by reinink** [comment]
Tagged! https://github.com/thephpleague/plates/releases/tag/3.2.0
