### ISSUE TITLE
A bug in $template->render('folderName/templateFile'); ?

### ISSUE THREAD

**Issue by 7php** [thephpleague/plates#76]
I notice something very weird:

assuming:
The calling block is something like:
```
    $template = new \League\Plates\Engine($container->get('/path/to/view'));
    $template->render('front/index');
```

and the folder structure is:
```
path/to/view
|__ Front
|     |__ index.tpl.php
|__ anotherTemplate.tpl.php
```

On my local LAMP stack, if I call the folder name **'Front'** with lowercase as in **$template->render('front/index');**
It works fine!

BUT, on a production server like an AWS LAMP stack, unless I put the folder name 'as-is' with the first Cap letter as in **$template->render('Front/index');**
it will not work. (which does make sense)

**QU: Any ideas why on my local machine it does work although not making sense?**

**Comment by rogerroelofs** [comment]
It's the underlying OS. Some are case insensitive while Linux is case
sensitive.

**Comment by 7php** [comment]
but my local machine was a Docker box with Ubuntu while the AWS was also a Ubuntu.
One difference is that locally, my host machine is Mac.

**Comment by rogerroelofs** [comment]
I don't know enough about how Dockery shares the source folder  to speak to
that    I know  MacOS is case insensitive    I lowercase everything  to
avoid this class of problems    it will also cause you grief using a git
repo across OSes

**Comment by 7php** [comment]
Thanks for the info, it makes sense now.
Thanks Roger, appreciate!
