### ISSUE TITLE
Insert template relative to current

### ISSUE THREAD

**Issue by oscarotero** [thephpleague/plates#79]
Hi.
I use directories to organize my templates and I miss an option to insert a template using a relative path. Something like this:

``` php
<?php $this->insert('./my-template') ?>
```

This should be useful to avoid repetitions and to allow move templates without break them. What do you think?

**Comment by funivan** [comment]
`class Name` is hardcoded in the plates template. Overwriting this class can solve your problem. I have similar problem with the `Name` class

**Comment by ragboyjr** [comment]
A naming strategy system discussed in #130 would also work for this. I'll keep this ticket around though because we'd need to develop a system that would work for both types of issues.

**Comment by mollierobbert** [comment]
+1 Relative imports are a must-have for a system with 200+ template files.

**Comment by ragboyjr** [comment]
Closing in favor of #170
